//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASM.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Topic
    {
        public string TopicID { get; set; }
        public string Topic_Name { get; set; }
        public string Description { get; set; }
        public string CourseID { get; set; }
        public string UserID { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual User_Account User_Account { get; set; }

        [NotMapped]
        public List<Course> coCollection { get; set; }
        [NotMapped]
        public List<User_Account> IdCollection3 { get; set; }
    }
}
